site_name: Jupyter-JSC Documentation
theme:
  name: material 
  features:
    - nagivation.tabs
    - navigation.sections
    - navigation.collapse
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  logo: images/logo.png
  palette:
    - scheme: fzj
      primary: teal
      accent: purple

plugins:
  - mkdocs-jupyter
  - social
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/style.css

extra:
  logo: "images/logo.png"

copyright: |
  &copy; 2024 Forschungszentrum Jülich | <a href="https://www.fz-juelich.de/en/legal-notice" target="_blank">Legal Notice</a>

nav:
  - General:
    - Overview: index.md
    - Authentication: authentication.md
    - Available Resources and Tools: features.md
  - For Users:
    - JupyterLab 4.2: users/jupyterlab/4.2/index.md
    - Custom Docker Images: users/jupyterlab/customdockerimage/index.md
    - Repo2Docker ( Binder ): users/jupyterlab/repo2docker/index.md
    - Useful Tips & Tricks: users/misc.md
  - Support: support.md
