# Generated by Django 3.2.10 on 2021-12-22 11:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0003_rename_date_remotemodel_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tunnelmodel",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
