# Generated by Django 3.2.10 on 2021-12-22 11:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteModel",
            fields=[
                ("hostname", models.TextField(primary_key=True, serialize=False)),
                ("status", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
