# Generated by Django 3.2.10 on 2021-12-22 11:27
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0005_rename_last_update_remotemodel_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remotemodel",
            old_name="status",
            new_name="running",
        ),
    ]
