# Generated by Django 3.2.10 on 2022-02-10 06:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0006_rename_status_remotemodel_running"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tunnelmodel",
            name="backend_id",
        ),
        migrations.AddField(
            model_name="tunnelmodel",
            name="startuuidcode",
            field=models.TextField(
                default="default", primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
