# Generated by Django 3.2.10 on 2022-02-10 11:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0007_auto_20220210_0610"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RemoteModel",
        ),
    ]
