# Generated by Django 3.2.10 on 2022-03-02 07:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0008_delete_remotemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="tunnelmodel",
            name="svc_port",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
