# Generated by Django 3.2.16 on 2023-03-03 10:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0012_tunnelmodel_tunnel_pod"),
    ]

    operations = [
        migrations.AddField(
            model_name="tunnelmodel",
            name="jhub_credential",
            field=models.TextField(
                default="jupyterhub", verbose_name="jhub_credential"
            ),
        ),
    ]
