# Generated by Django 4.2.7 on 2023-12-12 15:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0013_tunnelmodel_jhub_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="tunnelmodel",
            name="jhub_userid",
            field=models.TextField(default="0"),
        ),
    ]
